name: twitter_clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  appwrite: ^9.0.1
  flutter_riverpod: ^2.3.2
  go_router: ^10.1.0
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  streaming_shared_preferences: ^2.0.0
  flutter_svg: ^2.0.4
  multiple_result: ^5.1.0
  freezed_annotation: ^2.2.0
  rxdart: ^0.27.7
  flutter_native_splash: ^2.2.19
  cached_network_image: ^3.2.3
  image_picker: ^1.0.2
  carousel_slider: ^4.2.1
  timeago: ^3.3.0
  any_link_preview: ^3.0.0
  like_button: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svgs/
